// Entity list for company name detection
export const ENTITIES = [
  'LIMITED', 'LTD', 'LTD.', 'PRIVATE LIMITED', 'PVT LTD', 'PVT. LTD', 'PVT LTD.',
  'INCORPORATION', 'INC', 'INC.',
  'CORPORATION', 'CORP', 'CORP.',
  'LIMITED LIABILITY PARTNERSHIP', 'LLP', 'LLP.',
  'LIMITED LIABILITY COMPANY', 'LLC',
  'LIMITED PARTNERSHIP', 'LP', 'LP.',
  'COMPANY', 'CO', 'CO.',
  'PROGRAMMABLE LOGIC CONTROLLER', 'PLC', 'PLC.',
  'AGENCY', 'AG', 'AG.',
  'ORGANIZATION', 'ORG', 'ORG.',
  'GESELLSCHAFT MIT BESCHRÄNKTER HAFTUNG', 'GMBH',
  'LIMITED LIABILITY', 'LL',
  'SALAZAR RESOURCES LIMITED', 'SRL', 'SRL.'
];